[package]
name = "neli"
version = "0.5.3"
edition = "2018"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]
description = "Type safe netlink library written in Rust"
license = "BSD-3-Clause"
repository = "https://github.com/jbaublitz/neli"
keywords = ["netlink"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "LICENSE",
]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "neli"
path = "src/lib.rs"

[dependencies]
byteorder = "1.2"
libc = "0.2.82"

[dependencies.log]
version = "0.4"
optional = true

[dependencies.simple_logger]
version = "1.6.0"
optional = true

[dependencies.lazy_static]
version = "1.4"
optional = true

[dependencies.tokio]
version = "1"
features = ["io-util", "rt-multi-thread", "sync", "net"]
optional = true

[dependencies.tokio-stream]
version = "0.1"
optional = true

[dependencies.futures-util]
version = "0.3"
optional = true

[features]
default = []
async = ["tokio", "tokio-stream", "futures-util"]
logging = ["log", "simple_logger", "lazy_static"]
netfilter = []
